# Generated by Django 4.2.7 on 2023-12-28 21:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("referrals", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="referral",
            name="referring_user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="referrals_made",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
