# Generated by Django 4.2.7 on 2023-12-12 01:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Tasks",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("link", models.URLField(blank=True, null=True)),
                ("number_of_completions", models.PositiveIntegerField(default=1)),
                ("display_order", models.PositiveIntegerField()),
                ("no_user_completions", models.PositiveIntegerField(default=0)),
                ("awaiting_completions", models.PositiveIntegerField(default=0)),
                (
                    "prerequisite",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="dependent_tasks",
                        to="tasks.tasks",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("AVAILABLE", "Available"),
                            ("LOCKED", "Locked"),
                            ("HIDDEN", "Hidden"),
                            ("COMPLETED", "Completed"),
                        ],
                        max_length=10,
                    ),
                ),
                ("completions", models.PositiveIntegerField(default=0)),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="tasks.tasks"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
