# Generated by Django 4.2.7 on 2024-01-02 23:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Tasks",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, max_length=255)),
                ("uri", models.URLField(blank=True, null=True)),
                ("queue_jumps", models.PositiveBigIntegerField(default=10)),
                (
                    "max_repetitions",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Maximum number of times a user can repeat a task.",
                    ),
                ),
                ("display_order", models.PositiveIntegerField(unique=True)),
                (
                    "total_global_completions",
                    models.PositiveIntegerField(
                        default=0, help_text="Total completions by all users."
                    ),
                ),
                (
                    "pending_global_completions",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Number of users who have this task available but have not completed it.",
                    ),
                ),
                ("is_hidden", models.BooleanField(default=False)),
                (
                    "target_demographic",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("EXPAT", "Expat"),
                            ("PARENT", "Parent"),
                            ("SPORTS", "Sports"),
                            ("FESTIVAL", "Festival"),
                        ],
                        max_length=25,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="UserTasks",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("AVAILABLE", "Available"),
                            ("LOCKED", "Locked"),
                            ("HIDDEN", "Hidden"),
                            ("COMPLETED", "Completed"),
                        ],
                        max_length=10,
                    ),
                ),
                ("repetitions", models.PositiveIntegerField(default=0)),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="tasks.tasks"
                    ),
                ),
            ],
        ),
    ]
