# Generated by Django 4.2.7 on 2023-12-28 23:40

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("tasks", "0002_rename_link_tasks_uri_tasks_created_at_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="UserTask",
            new_name="UserTasks",
        ),
    ]
