# Generated by Django 4.2.7 on 2023-12-28 23:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0003_rename_usertask_usertasks"),
    ]

    operations = [
        migrations.RenameField(
            model_name="tasks",
            old_name="number_of_completions",
            new_name="max_user_completions",
        ),
        migrations.RenameField(
            model_name="tasks",
            old_name="awaiting_completions",
            new_name="remaining_global_completions",
        ),
        migrations.RenameField(
            model_name="tasks",
            old_name="no_user_completions",
            new_name="total_global_completions",
        ),
    ]
