# Generated by Django 4.2.7 on 2023-12-28 23:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "tasks",
            "0004_rename_number_of_completions_tasks_max_user_completions_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tasks",
            name="remaining_global_completions",
        ),
        migrations.AddField(
            model_name="tasks",
            name="pending_global_completions",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Number of users who have this task available but have not completed it.",
            ),
        ),
        migrations.AlterField(
            model_name="tasks",
            name="max_user_completions",
            field=models.PositiveIntegerField(
                default=1, help_text="Maximum completions allowed per user."
            ),
        ),
        migrations.AlterField(
            model_name="tasks",
            name="total_global_completions",
            field=models.PositiveIntegerField(
                default=0, help_text="Total completions by all users."
            ),
        ),
    ]
