# Generated by Django 4.2.7 on 2023-12-29 00:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0005_remove_tasks_remaining_global_completions_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tasks",
            name="is_hidden",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="tasks",
            name="target_demographic",
            field=models.CharField(
                blank=True,
                choices=[
                    ("EXPAT", "Expat"),
                    ("PARENT", "Parent"),
                    ("SPORTS", "Sports"),
                    ("FESTIVAL", "Festival"),
                ],
                max_length=25,
            ),
        ),
    ]
