# Generated by Django 4.2.7 on 2023-12-29 03:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0006_tasks_is_hidden_tasks_target_demographic"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tasks",
            name="description",
            field=models.TextField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="tasks",
            name="prerequisite",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="dependent",
                to="tasks.tasks",
            ),
        ),
        migrations.AlterField(
            model_name="usertasks",
            name="completions",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
