# Generated by Django 4.2.7 on 2023-12-29 16:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0007_alter_tasks_description_alter_tasks_prerequisite_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tasks",
            name="max_user_completions",
        ),
        migrations.RemoveField(
            model_name="usertasks",
            name="completions",
        ),
        migrations.AddField(
            model_name="tasks",
            name="max_repetitions",
            field=models.PositiveIntegerField(
                default=1, help_text="Maximum number of times a user can repeat a task."
            ),
        ),
        migrations.AddField(
            model_name="usertasks",
            name="repetitions",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
