# Generated by Django 4.2.7 on 2024-01-02 23:31

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Floater",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("display_name", models.CharField(max_length=25)),
                ("display_description", models.TextField(default="enter some text")),
                ("display_order", models.IntegerField(unique=True)),
                ("short_description", models.CharField(default="short")),
                (
                    "tier",
                    models.CharField(
                        choices=[
                            ("ST", "Starter Pack"),
                            ("TT", "Tried & True"),
                            ("BD", "Baddies"),
                            ("GD", "God Tier"),
                        ],
                        default="ST",
                        max_length=2,
                    ),
                ),
                (
                    "avatar_icon_1x",
                    models.ImageField(
                        blank=True, null=True, upload_to="floaters/icons"
                    ),
                ),
                (
                    "avatar_icon_2x",
                    models.ImageField(
                        blank=True, null=True, upload_to="floaters/icons"
                    ),
                ),
                (
                    "avatar_hero_1x",
                    models.ImageField(
                        blank=True, null=True, upload_to="floaters/heroes"
                    ),
                ),
                (
                    "avatar_hero_2x",
                    models.ImageField(
                        blank=True, null=True, upload_to="floaters/heroes"
                    ),
                ),
                (
                    "avatar_badge_1x",
                    models.ImageField(
                        blank=True, null=True, upload_to="floaters/badges"
                    ),
                ),
                (
                    "avatar_badge_2x",
                    models.ImageField(
                        blank=True, null=True, upload_to="floaters/badges"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FloaterCollection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "floaters",
                    models.ManyToManyField(
                        blank=True, related_name="collections", to="floaters.floater"
                    ),
                ),
            ],
        ),
    ]
