# Generated by Django 4.2.7 on 2023-11-28 20:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("floaters", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="floaters",
            name="display_description",
            field=models.TextField(default="enter some text"),
        ),
        migrations.AddField(
            model_name="floaters",
            name="display_order",
            field=models.IntegerField(default=0, unique=True),
        ),
        migrations.AddField(
            model_name="floaters",
            name="short_description",
            field=models.CharField(default="enter some text", max_length=30),
        ),
        migrations.AddField(
            model_name="floaters",
            name="tier",
            field=models.CharField(
                choices=[
                    ("ST", "Starter Pack"),
                    ("TT", "Tried & True"),
                    ("BD", "Baddies"),
                    ("GD", "God Tier"),
                ],
                default="ST",
                max_length=2,
            ),
        ),
    ]
