# Generated by Django 4.2.7 on 2024-01-02 23:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("floaters", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="floatercollection",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="floater_collection",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
