# Generated by Django 4.2.7 on 2023-11-28 20:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "floaters",
            "0002_floaters_display_description_floaters_display_order_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="floaters",
            name="short_description",
            field=models.CharField(default="short", max_length=30),
        ),
    ]
