# Generated by Django 4.2.7 on 2023-11-28 20:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("floaters", "0004_alter_floaters_short_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="floaters",
            name="short_description",
            field=models.CharField(default="short"),
        ),
    ]
