# Generated by Django 4.2.7 on 2023-11-28 20:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("floaters", "0005_alter_floaters_short_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="floaters",
            name="avatar_badge_1x",
            field=models.ImageField(blank=True, null=True, upload_to="floaters/badges"),
        ),
        migrations.AddField(
            model_name="floaters",
            name="avatar_badge_2x",
            field=models.ImageField(blank=True, null=True, upload_to="floaters/badges"),
        ),
        migrations.AddField(
            model_name="floaters",
            name="avatar_hero_1x",
            field=models.ImageField(blank=True, null=True, upload_to="floaters/heroes"),
        ),
        migrations.AddField(
            model_name="floaters",
            name="avatar_hero_2x",
            field=models.ImageField(blank=True, null=True, upload_to="floaters/heroes"),
        ),
        migrations.AddField(
            model_name="floaters",
            name="avatar_icon_1x",
            field=models.ImageField(blank=True, null=True, upload_to="floaters/icons"),
        ),
        migrations.AddField(
            model_name="floaters",
            name="avatar_icon_2x",
            field=models.ImageField(blank=True, null=True, upload_to="floaters/icons"),
        ),
    ]
