# Generated by Django 4.2.7 on 2023-12-30 00:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("floaters", "0008_floatercollection"),
    ]

    operations = [
        migrations.AlterField(
            model_name="floater",
            name="display_name",
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name="floater",
            name="display_order",
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name="floatercollection",
            name="floaters",
            field=models.ManyToManyField(
                blank=True, related_name="collections", to="floaters.floater"
            ),
        ),
    ]
