# Generated by Django 4.2.7 on 2024-01-02 23:31

import apps.utils.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DeviceSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ip", models.GenericIPAddressField()),
                ("session_start", models.DateTimeField(auto_now_add=True)),
                ("session_end", models.DateTimeField(blank=True, null=True)),
                (
                    "timezone",
                    models.CharField(
                        max_length=100, validators=[apps.utils.models.validate_timezone]
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="UserDevice",
            fields=[
                (
                    "device_fingerprint",
                    models.CharField(max_length=128, primary_key=True, serialize=False),
                ),
                ("device_model", models.CharField(max_length=100)),
                ("device_brand", models.CharField(max_length=100)),
                ("os_name", models.CharField(max_length=100)),
                ("os_version", models.CharField(max_length=50)),
                ("screen_width", models.IntegerField()),
                ("screen_height", models.IntegerField()),
                ("locales", models.JSONField(default=list)),
                ("currencies", models.JSONField(default=list)),
                ("font_scale", models.FloatField()),
                ("accesibility_settings", models.JSONField(default=dict)),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
            ],
        ),
    ]
