# Generated by Django 4.2.7 on 2023-11-28 22:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_user_floater"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="active_tier",
            field=models.IntegerField(
                choices=[(1, 1), (2, 2), (3, 3), (4, 4)], default=1
            ),
        ),
    ]
