# Generated by Django 4.2.7 on 2023-11-29 16:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_user_active_tier"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="active_tier",
        ),
        migrations.RemoveField(
            model_name="user",
            name="floater",
        ),
    ]
