# Generated by Django 4.2.7 on 2023-11-29 18:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0005_user_user_id_alter_user_email"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="user_id",
        ),
    ]
