# Generated by Django 4.2.7 on 2023-11-29 20:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0007_user_referral_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="referral_count",
            field=models.IntegerField(default=0),
        ),
    ]
