# Generated by Django 4.2.7 on 2023-11-29 21:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0008_user_referral_count"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[],
        ),
    ]
