# Generated by Django 4.2.7 on 2023-12-15 15:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):
    dependencies = [
        ("floaters", "0007_rename_floaters_floater"),
        ("users", "0010_user_created_at_alter_user_date_joined"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="tier_access",
            field=models.IntegerField(default=1, verbose_name="Tier access"),
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dob", models.DateField(verbose_name="Date of Birth")),
                (
                    "phyiscal_location",
                    django_countries.fields.CountryField(
                        max_length=2, verbose_name="Country"
                    ),
                ),
                (
                    "pronouns",
                    models.CharField(
                        choices=[
                            ("he", "He/Him/His"),
                            ("she", "She/Her/Hers"),
                            ("they", "They/Them/Theirs"),
                            ("other", "Other"),
                        ],
                        max_length=30,
                        verbose_name="Pronouns",
                    ),
                ),
                (
                    "is_expat",
                    models.BooleanField(default=False, verbose_name="Is Expat"),
                ),
                (
                    "is_parent",
                    models.BooleanField(default=False, verbose_name="Is Parent"),
                ),
                (
                    "is_sports_traveler",
                    models.BooleanField(
                        default=False, verbose_name="Is Sports Traveler"
                    ),
                ),
                (
                    "is_festival_traveler",
                    models.BooleanField(
                        default=False, verbose_name="Is Festival Traveler"
                    ),
                ),
                ("is_student", models.BooleanField(default=False)),
                ("is_vip", models.BooleanField(default=False)),
                ("is_company_of_interest", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "avatar_id",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="floaters.floater",
                        verbose_name="Floater ID",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
