# Generated by Django 4.2.7 on 2023-12-15 16:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0011_user_tier_access_userprofile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="dob",
            field=models.DateField(null=True, verbose_name="Date of Birth"),
        ),
    ]
