# Generated by Django 4.2.7 on 2023-12-15 17:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0012_alter_userprofile_dob"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(
                blank=True, max_length=150, null=True, verbose_name="username"
            ),
        ),
    ]
